yolo_weights: "weights/yolov8/yolov8n.pt"                   # path to yolo weight
reid_weights: "weights/reid/osnet_x0_25_msmt17.pt"          # path to reid weight
tracking_method: "bytetrack"                                # strongsort, ocsort, bytetrack
classes:                                                    # class 0 is person, 1 is bycicle, 2 is car... 79 is oven
imgsz: [640]                                                # inference size h,w
vid_stride: 1                                               # video frame-rate stride
device: "cpu"                                               # cuda device, i.e. 0 or 0,1,2,3 or cpu

tracking_config:                                            # config for tracking process
conf_thres:                                                 # confidence threshold in NMS
iou_thres:                                                  # IOU threshold in NMS
max_det:                                                    # maximum detections per image
half:                                                       # use FP16 half-precision inference
dnn:                                                        # use OpenCV DNN for ONNX inference
agnostic_nmsp:                                              # class-agnostic NMS
augment:                                                    # augmented inference
update:                                                     # update all models

